### ISSUE TITLE
always suggests numbers after "=" or "-"

### ISSUE THREAD

**Issue by czhiling** [Zinggi/DictionaryAutoComplete#14] opened 2015-02-04 08:50 UTC
Thank you very much for the nice plugin. It's very useful.

I encountered a problem. I always enable the autocomplete in markdown. But when I input "=" or "-", the autocomplete window always suggest me some numbers. Could you please help solve this problem?

![pasted_image_04_02_15_17_44](https://cloud.githubusercontent.com/assets/218637/6037357/1819b8a6-ac96-11e4-8aeb-dabedd87f644.gif)

**Comment by Zinggi** [comment] 2015-02-04 10:13
This does not happen for me. Maybe you have `"="` and `"-"` in your `"auto_complete_triggers": [ {"selector": "text.html", "characters": "<=-"} ],`?

The numbers come from the dictionary file itself. For some reason they are included inside the dictionary file, even though I see absolutely no reason why to include numbers in a dictionary...

I could theoretically filter numbers out when reading in the dictionary, but then you'd get `0th, 1st, 1th, 2nd, ...` which isn't mutch better.

**Comment by czhiling** [comment] 2015-02-04 12:09
Thank you very much for your quick reply. According to your hints, I download the latest dictionary (English) from https://github.com/titoBouzout/Dictionaries to my "Packages/User". It seems the annoyance disappeared:)

**Comment by Zinggi** [comment] 2015-02-04 12:41
That's very weird, this dictionary also includes those numbers.
My guess is still that there was/is something wrong with your `auto_complete_triggers`, as typing `=` shouldn't trigger the autocompletions.
But if that really worked for you, than great!

**Comment by czhiling** [comment] 2015-02-04 13:26
Sorry, I was wrong. The problem is not solved. I do not have "auto_complete_triggers" in my configuration files. And  not only "+" and "-", but also a space trigger the suggestion window. Is there any way to exclude symbol and space from trigger? Is it possible it's due to the combination effect with other plugin? I also have markdownediting and some other plguin installed. However, if I disable DictionaryAutoComplete, the numbers suggestion disappeared. 

![pasted_image_04_02_15_21_58](https://cloud.githubusercontent.com/assets/218637/6041148/d373fdc0-acbc-11e4-9048-866240b91d8a.gif)

**Comment by Zinggi** [comment] 2015-02-04 13:51
How does your: "auto_complete_selector" look like? 
I just installed markdownediting and I still only get sane triggers, e.g. letters. So it can't be this package.

BTW, what theme is that? Looks good ;)

**Comment by czhiling** [comment] 2015-02-04 14:02
the only line in my DictionaryAutoComplete.sublime-settings is the following:
`	"auto_complete_selector": "text.html.markdown, text.plain, text.tex.latex, text.tex",`

I have no idea what to do now. Maybe I will have a more careful check this weekend.

The theme is from https://github.com/kkga/spacegray :)

**Comment by Zinggi** [comment] 2015-02-04 14:21
I don't think this line in that file has any effect at all.

The usual location is `Preferences` -> `Settings - User`.
There you might also find the `"auto_complete_triggers"`

**Comment by czhiling** [comment] 2015-02-05 02:10
I only found one line in my default settings:

 `  "auto_complete_triggers": [ {"selector": "text.html", "characters": "<"} ],`

Is it possible to remove space from trigger?

**Comment by Zinggi** [comment] 2015-02-15 16:06
Hey sorry for not replying earlier, I was gone for holidays.

Hmm, sorry I really don't know what's the problem...
It might be that another addon is causing this, but I don't know.
You could try downloading a fresh portable version of Sublime and slowly install your other addons one after another until this happens again.

I tried on a fresh installation with no other addons and what you describe didn't happen.

**Comment by mkanai** [comment] 2015-04-14 07:21
FYI: I just found out `SublimeCodeIntel` seems to trigger these weird completions for Markdown.

https://github.com/SublimeCodeIntel/SublimeCodeIntel/issues/471

**Comment by czhiling** [comment] 2015-04-14 12:30
Hello Kanai-san,

Thank you very much for the information. As soon as I disabled `SublimeCodeIntel`, it seems the annoyance disappeared.

**Comment by Zinggi** [comment] 2015-04-24 13:37
On the top of my head not, sorry. I'm currently on a long holiday so I won't be trying to figure anything out for at least 3 months

**Comment by czhiling** [comment] 2015-04-25 02:40
Thank you for the reply. 

No problem, In the meantime, I disabled the `SublimeCodeIntel` if I need `DictionaryAutoComplete`.

Have a nice holiday!! I envy you!

**Comment by mkanai** [comment] 2015-04-25 03:53
Well, according to [this thread](https://github.com/SublimeCodeIntel/SublimeCodeIntel/issues/471), using `CodeComplice` instead of `SublimeCodeIntel` solves the problem.
https://github.com/spectacles/CodeComplice

So far, it works fine for me.

**Comment by Zinggi** [comment] 2015-07-17 16:21
Since I don't think there is anything that I can do to prevent this, I will close this issue.

It seems to be caused by combining SublimeCodeIntel with my plugin.
SublimeCodeIntel triggers the completion window and DictionaryAutoComplete fills the window with nonsense numbers, because these numbers are found in the standard dictionary file.

A possible solution, as suggested by mkanai, is to install [CodeComplice](https://github.com/spectacles/CodeComplice) instead of  SublimeCodeIntel.

**Closed by Zinggi** 2015-07-17 16:21 UTC
