### ISSUE TITLE
Is it possible to disable the autocompletion if I just simply type a space?

### ISSUE THREAD

**Issue by Voyga** [Zinggi/DictionaryAutoComplete#18] opened 2015-09-15 11:55 UTC
![snip20150915_6](https://cloud.githubusercontent.com/assets/9929523/9875778/8401d1b4-5be3-11e5-9f94-91506687fd41.png)
Every time I type a space this will show up which is extremely ugly. Is there any way to prevent this?

**Comment by Zinggi** [comment] 2015-09-15 15:05
This seems to be a duplicate of https://github.com/Zinggi/DictionaryAutoComplete/issues/14.
I can only guess that there is another plugin triggering auto-complete suggestions when it shouldn't. A likely candidate seem to be `SublimeCodeIntel`.
As there is most likely nothing I can do to prevent this from happening I'm gonna close this.

**Closed by Zinggi** 2015-09-15 15:05 UTC
